### ISSUE TITLE
Is it possible to batch download from Google drive and mega?

### ISSUE THREAD

**Issue by Ramton03** [TachibanaGeneralLaboratories/download-navi#10]

**Comment by proninyaroslav** [comment]
GDrive requires authorization. Authorization so far in the plans #7. I think Mega has the same problem. If you provide a link I can check it.

**Comment by c-sanchez** [comment]
Can be nice have the abbility to download mega links from navi directly, for now just from browsers and some "special" download managers like jodownloader, ponydroid, etc are cappable.

Maybe this can help?
https://megatools.megous.com/

**Comment by proninyaroslav** [comment]
We will not make specialized tools for services. Maximum - make a very simple web browser to open links.

**Comment by Pentaphon** [comment]
@Ramton03 Looks like you will have to use https://megatools.megous.com/ instead.
