### ISSUE TITLE
[Feature request] ESNI support

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [TachibanaGeneralLaboratories/download-navi#100]
Firefox announced support for ESNI for a long time, and the usage of ESNI is also encouraged by Cloudflare. It’s reasonable to add this support if server accepts such header.
See:
https://blog.mozilla.org/security/2018/10/18/encrypted-sni-comes-to-firefox-nightly/
https://blog.cloudflare.com/encrypt-that-sni-firefox-edition/

**Comment by vdbhb59** [comment]
Actually CF and FF both have gone berserk and are not safe for people with needs of privacy. ESNI is another a** protocol. With open sourced and FOSS based apps, this protocol is cancer.

**Comment by proninyaroslav** [comment]
Navi isn't targeted to support private/proprietary protocols, including Cloudflare. If Android has native support, then this will be supported in Navi too.
