### ISSUE TITLE
[Bug, Question?] Insert from Clipboard not working on Android 10

### ISSUE THREAD

**Issue by billie80** [TachibanaGeneralLaboratories/download-navi#101]
I think with the 1.2 release the functionality to insert the contents of the clipboard if it contains a valid URL was added in this commit https://github.com/TachibanaGeneralLaboratories/download-navi/commit/067262cee1cb84d4121b4043d5db47f754e881d8. This new functionality is really nice as one copies the URL in almost 100% of the cases instead if typing some URL. 

Previously I used Download Navi on a Android 6 device. Here this worked without problems.
Now I got a new phone which comes with Android 10 where this stopped working.

Am I just missing some option in the settings? Or has this to do with changed permissions betwen Android 6 and 10?

**Comment by proninyaroslav** [comment]
Yes, I noticed this problem too. I will try to fix it.

**Comment by proninyaroslav** [comment]
Unfortunately, it's not a bug:
> **Limited access to clipboard data**
> Unless your app is the default input method editor (IME) or is the app that currently has focus, your app cannot access clipboard data on Android 10 or higher.

https://developer.android.com/about/versions/10/privacy/changes#clipboard-data

In other words: Android 10 brought restrictions on apps accessing the clipboard. Now, only the app that currently has focus or the default input method editor (such as the keyboard) can access that data. If you try to access it under any other circumstance, the system will behave as if the clipboard was empty.

The only workaround is to listen for window focus changes and check the clipboard: https://github.com/TachibanaGeneralLaboratories/download-navi/commit/bf7e17e7fe1433f1cacb7624f95979abf2a79109

**Comment by proninyaroslav** [comment]
P.S: old behavior won't work in this case https://github.com/TachibanaGeneralLaboratories/download-navi/commit/067262cee1cb84d4121b4043d5db47f754e881d8

**Comment by billie80** [comment]
With the Clipboard Button in Version 1.3 it works again.
