### ISSUE TITLE
Connection closed by peer

### ISSUE THREAD

**Issue by ghost** [TachibanaGeneralLaboratories/download-navi#102]
site url:- https://fatdino.itch.io/unrealracing

download navi

![dn](https://user-images.githubusercontent.com/63355586/88823675-02e12880-d1ce-11ea-8130-711f846eb360.jpg)

ucweb

![uc1](https://user-images.githubusercontent.com/63355586/88823732-18eee900-d1ce-11ea-9ba4-99bf4a9c613a.jpg)

![uc2](https://user-images.githubusercontent.com/63355586/88823792-2c9a4f80-d1ce-11ea-8a17-68ac2cb8d1ed.jpg)

pure browser

![pure1](https://user-images.githubusercontent.com/63355586/88823855-3e7bf280-d1ce-11ea-99e9-b01665556cde.jpg)

![pure2](https://user-images.githubusercontent.com/63355586/88823920-505d9580-d1ce-11ea-82ab-e4c83e7b6f5a.jpg)

ucweb and pure browser get the file faster but once i add them to the download waits few seconds before starting the download and not even once says "Connection closed by peer".

**Comment by abelfn** [comment]
anything on this

**Comment by abelfn** [comment]
In the past i was getting the above error now its is, server returned HTTP 403 code.Any update on this

**Comment by abelfn** [comment]
they say i have to add useragent in httpurlconnection but it is not working

**Comment by proninyaroslav** [comment]
@abelfn 
User Agent can be added or selected at the stage of adding a download.

**Comment by abelfn** [comment]
I know that but that will not fix it

**Comment by proninyaroslav** [comment]
Fixed by https://github.com/TachibanaGeneralLaboratories/download-navi/commit/e98ab1479bf73bb4d5d23c51a8c8a2df585e6490
