### ISSUE TITLE
notification when downloads get paused

### ISSUE THREAD

**Issue by avie25000** [TachibanaGeneralLaboratories/download-navi#106]
can notification when download get paused to be cleared out?

here an example (UC Browser download) :
![ezgif-6-1aa153c7a287](https://user-images.githubusercontent.com/70332632/91459580-fcb79800-e8b0-11ea-8014-955e1ab9852e.gif)

and here the navi downloader : 
![ezgif-6-98989c5797d9](https://user-images.githubusercontent.com/70332632/91459848-56b85d80-e8b1-11ea-95c8-4e48aaaaf618.gif)

I always pause for a long time, because of the daily quota. the pause notification that can't be cleared is quite annoying for me.  

If I do stop, I can't find anything on the stopped status! I've lost a file download that has reached 2GB due to accidentally pressed stop. or maybe this is another issue?

thanks! 

Device: Redmi Note 4X
OS: Android 9.0 Pie
Version: 1.2

**Comment by proninyaroslav** [comment]
Fixed 78f921f
