### ISSUE TITLE
Allow intercepting large drive links

### ISSUE THREAD

**Issue by Nickdv9** [TachibanaGeneralLaboratories/download-navi#11]
Links from google drive that are > than 400-500mb are not downloaded, instead it only downloads the webpage. A possible solution would be to use webview to intercept these links.

Test: 
-> Open Navi, add a drive link with file size > than 500mb
-> Add the URL, connect and start download

Result: 
Downloads the webpage instead

Attaching a few screenshots for some reference below:
![Screenshot_20190421-083111_Download_Navi](https://user-images.githubusercontent.com/17958198/56464874-ed355e80-63e1-11e9-9ebb-1ce9a556b40c.png)
![Screenshot_20190421-083056_Download_Navi](https://user-images.githubusercontent.com/17958198/56464877-f292a900-63e1-11e9-9c49-945595631582.png)

**Comment by Ramton03** [comment]
Me too.

**Comment by proninyaroslav** [comment]
GDrive requires authorization. Authorization so far in the plans https://github.com/TachibanaGeneralLaboratories/download-navi/issues/7
