### ISSUE TITLE
(Feature Request) Download Pieces per Download

### ISSUE THREAD

**Issue by Raul1198** [TachibanaGeneralLaboratories/download-navi#118]
Can we get an option to set No of pieces for every download by default insted of changing for ecah one, like in ADM this 
![Screenshot_20200908-233656630 (1)](https://user-images.githubusercontent.com/29801315/92512369-4fd40800-f22c-11ea-9db3-c567e0de4e8b.jpg) like here the no of thread is set to 9 so every download will have automatically 9 thread. So like this in Navi we could set 16 ( max available ) as max thread for every downloads. As I have tried with Navi downloading a file with more thread is faster than 1 thread

**Comment by proninyaroslav** [comment]
In 1.3 version, you can set 16 pieces and these settings will not be reset next time You can set 16 parts and these settings will not be reset next time
