### ISSUE TITLE
Not getting the correct file name and receipt of the file extension from dropbox

### ISSUE THREAD

**Issue by abelfn** [TachibanaGeneralLaboratories/download-navi#119]
https://www.dropbox.com/s/m1ms33hjf03gm8p/mm-unlimitededition-1-4-2.zip?dl=0&file_subpath=%2Funlimitededition

download navi

![dndb](https://user-images.githubusercontent.com/70645835/92570062-42bc1680-f236-11ea-9a00-a245aba5b312.jpg)

pure browser

![pbdb](https://user-images.githubusercontent.com/70645835/92569584-ad208700-f235-11ea-8dce-2db31a974423.jpg)

**Comment by proninyaroslav** [comment]
Please try to build with this commit https://github.com/TachibanaGeneralLaboratories/download-navi/commit/80513d5fbdc95eae117d3f8cf1eb39a00a300263 and check again.

**Comment by abelfn** [comment]
![dn](https://user-images.githubusercontent.com/70645835/92691787-cfa4c400-f34b-11ea-8f06-b4bb02a970a5.jpg)

filename works but:-

ext
size:
pause and downloading by picese

not working!

**Comment by proninyaroslav** [comment]
Can you provide a link so I can test the extension parsing?
Multipart downloading and pause/resume only depends on the HTTP Range header that the server needs to support. If the server doesn't support - I can't do anything.

**Comment by abelfn** [comment]
I already provide you.use the above link.that is what i tried

**Comment by proninyaroslav** [comment]
Dropbox is passing the wrong content type. It seems like the parsing of the extension needs to be improved for such cases.
![Снимок экрана от 2020-09-10 12-04-07](https://user-images.githubusercontent.com/7840559/92707195-c4f32a80-f35d-11ea-951f-824dc5be2520.png)

**Comment by abelfn** [comment]
Nice job!
 Google drive file name is now being determined crrectly.
![dngd](https://user-images.githubusercontent.com/70645835/92715932-cecd5b80-f366-11ea-9f3b-587b6510888a.jpg)

**Comment by proninyaroslav** [comment]
It works correct. You probably tried to insert this link directly: `https://www.dropbox.com/s/m1ms33hjf03gm8p/mm-unlimitededition-1-4-2.zip...`, but that won't work as it is just an HTML page. Please use a browser.

![Screenshot_1599753976](https://user-images.githubusercontent.com/7840559/92759801-c3932380-f398-11ea-96b9-f2053543b83d.png)

**Comment by abelfn** [comment]
Very sorry, my mistake
