### ISSUE TITLE
(Bug) Download Speed

### ISSUE THREAD

**Issue by Raul1198** [TachibanaGeneralLaboratories/download-navi#131]
![Screenshot_20200914-111535116 (1)](https://user-images.githubusercontent.com/29801315/93058703-5aa7f600-f68d-11ea-85ea-8c6fbe4280da.jpg)
 As you can see the active download is showing 3.37MB/s whereas the actual speed is 6.67KB/s

**Comment by KaKi87** [comment]
Did or did not the download completed 2 seconds later after this screenshot ?

**Comment by Raul1198** [comment]
> Did or did not the download completed 2 seconds later after this screenshot ?

nope, it took some time about ~8-9 sec

**Comment by KaKi87** [comment]
Well, that would still imply a download speed of 1.05 MB/s so the Android meter is wrong anyway

**Comment by proninyaroslav** [comment]
The speed is calculated as the speed sum of all pieces. This happens approximately every 500 ms. 
The speed of each piece:
```
sampleDelta = currentTime - speedSampleStart;
sampleSpeed = ((currentBytes - speedSampleBytes) * 1000) / sampleDelta;
if (speed == 0) {
    speed = sampleSpeed;
else
    speed = ((piece.speed * 3) + sampleSpeed) / 4;
```

If you know how to improve this I would appreciate it. For now I close it.
