### ISSUE TITLE
Download Navi changing the correct URL to wrong URL resulting in HTTP 471 code

### ISSUE THREAD

**Issue by abelfn** [TachibanaGeneralLaboratories/download-navi#132]
Correct URL: 

https://ev.ypncdn.com/201706/30/13922231/720p_1500k_13922231/YouPorn_-_fake-hospital-doctors-thick-dick-stretches-hot-portuguese-pussy-lips.mp4?rate=350k&burst=1600k&validfrom=1603430700&validto=1603445100&hash=gm7jX%2BC0LD%2B67fi14SmPtJ2d4Rw%3D

LoaderDroid:

![LoaderDroid](https://user-images.githubusercontent.com/70645835/96972483-3ad2e000-151f-11eb-8521-bcb3ab23305d.jpg)

Wrong URL:

https://ev.ypncdn.com/201706/30/13922231/720p_1500k_13922231/YouPorn_-_fake-hospital-doctors-thick-dick-stretches-hot-portuguese-pussy-lips.mp4?burst=1600k&hash=gm7jX%2BC0LD%2B67fi14SmPtJ2d4Rw%3D&rate=350k&validfrom=1603430700&validto=1603445100

Download Navi:

![Download Navi](https://user-images.githubusercontent.com/70645835/96972592-5ccc6280-151f-11eb-88fa-694b3fb39b5e.jpg)

LoaderDroid:

![LoaderDroid](https://user-images.githubusercontent.com/70645835/96972633-6bb31500-151f-11eb-86da-36f9363ce578.jpg)

Check both url at:

http://www.rexswain.com/httpview.html

**Comment by abelfn** [comment]
The problem is NormalizeUrl

If i set public boolean sortQueryParameters = false; or remove it.

It will give me wrong url too

https://ev.ypncdn.com/201706/30/13922231/720p_1500k_13922231/YouPorn_-_fake-hospital-doctors-thick-dick-stretches-hot-portuguese-pussy-lips.mp4?rate=350k&validfrom=1603430700&burst=1600k&hash=gm7jX%2BC0LD%2B67fi14SmPtJ2d4Rw%3D&validto=1603445100

For now, I removed NormalizeUrl and it's working

//params.setUrl(NormalizeUrl.normalize(params.getUrl()));

 params.setUrl(params.getUrl());

I hope you will find a solution.

**Comment by abelfn** [comment]
It looks like NormalizeUrl class is the cause of many problems.

Testing url :- https://fatdino.itch.io/unrealracing

If i use NormalizeUrl

params.setUrl(NormalizeUrl.normalize(params.getUrl())); 

![itch err](https://user-images.githubusercontent.com/70645835/100324538-73f7e780-2fd8-11eb-8025-6681622d55a9.jpg)

If i remove NormalizeUrl

params.setUrl(params.getUrl());

![itch](https://user-images.githubusercontent.com/70645835/100324616-8eca5c00-2fd8-11eb-89ca-81ea06e06c26.jpg)

**Comment by abelfn** [comment]
Another one:-
Trying to download tiktok videos from

https://www.tubeoffline.com/download-TikTok-videos.php

Correct url:-

params.setUrl(params.getUrl());

https://v19.tiktokcdn.com/44003c9e3268c917ef0a01de93b372fb/5fe248c6/video/tos/useast2a/tos-useast2a-v-0068/0d1e0bbf540d442d9453fd6d6a792be6/?a=1180&br=7776&bt=3888&cd=0%7C0%7C0&cr=0&cs=0&cv=1&dr=0&ds=3&er=&l=2020122213275701011506903016172AB8&lr=&mime_type=video_mp4&qs=13&rc=ajw7c3hkc3FyeTMzOzczM0ApNTxrZTdxbjVpZTMzZzc8eWcvNmVfMWtoL2NfLS1hMTZzc2Q2NW1yXm1rbHMtLTUxLS06Yw%3D%3D&vl=&vr=

![correct](https://user-images.githubusercontent.com/70645835/102894997-fdce8f80-4474-11eb-9726-3bc5c509bc3d.jpg)


Wrong url:-

params.setUrl(NormalizeUrl.normalize(params.getUrl()))


https://v19.tiktokcdn.com/44003c9e3268c917ef0a01de93b372fb/5fe248c6/video/tos/useast2a/tos-useast2a-v-0068/0d1e0bbf540d442d9453fd6d6a792be6?a=1180&br=7776&bt=3888&cd=0%7C0%7C0&cr=0&cs=0&cv=1&dr=0&ds=3&l=2020122213275701011506903016172AB8&mime_type=video_mp4&qs=13&rc=ajw7c3hkc3FyeTMzOzczM0ApNTxrZTdxbjVpZTMzZzc8eWcvNmVfMWtoL2NfLS1hMTZzc2Q2NW1yXm1rbHMtLTUxLS06Yw%3D%3D

![wrong](https://user-images.githubusercontent.com/70645835/102895103-2d7d9780-4475-11eb-82a7-3d8af576dc0e.jpg)


I don't really understand the use of NormalizeUrl other than making problems.

**Comment by proninyaroslav** [comment]
I think I will cut the functionality of `NormalizeUrl`, leaving only basic things (for example, protocol normalization, www, slashes). Normalization is needed to unify the URL and prevent duplicates in the download list.

**Comment by proninyaroslav** [comment]
Fixed https://github.com/TachibanaGeneralLaboratories/download-navi/commit/e98ab1479bf73bb4d5d23c51a8c8a2df585e6490
