### ISSUE TITLE
Add option to completely disable built-in web browser.

### ISSUE THREAD

**Issue by stevenleeS0ht** [TachibanaGeneralLaboratories/download-navi#135]
Since this software is usually a complement of full-function web browser, the built-in web browser will be useless when there is already a web browser like Chrome or Firefox.

When there is a button to open built-in web browser, it sometimes cause wrong operation. 

I recommend to add option in setting to completely disable the built-in web browser.

@proninyaroslav , How do you think?

**Comment by proninyaroslav** [comment]
This option was originally here :) 
Settings -> Browser

![Screenshot_1619513496](https://user-images.githubusercontent.com/7840559/116214242-30540600-a74f-11eb-857b-e452cca1660f.png)
