### ISSUE TITLE
Error:Failed to determine if primary:

### ISSUE THREAD

**Issue by abelfn** [TachibanaGeneralLaboratories/download-navi#137]
Replace duplicate downloads not working if i change storage folder from system manager.

The first download works but the second time when i download the same file will remove it from storage and give error.

Folder Selection:-

![folderSelection](https://user-images.githubusercontent.com/70645835/102897257-c3ff8800-4478-11eb-9e41-978e7d9d89cb.jpg)

Behavior:-

![behavior](https://user-images.githubusercontent.com/70645835/102897346-e85b6480-4478-11eb-8330-b56a3d73d031.jpg)

Error:-

![error](https://user-images.githubusercontent.com/70645835/102897417-00cb7f00-4479-11eb-97eb-e189c74e9c57.jpg)

URL:- any 

ex:-

https://m.apkpure.com/via-browser-fast-light-geek-best-choice/mark.via.gp/download?from=details

**Comment by proninyaroslav** [comment]
I was unable to reproduce the problem, but I will leave it open for now.

**Comment by KaKi87** [comment]
Here's a systematically reproductible demo : https://drive.google.com/file/d/1xFLXAaydkb-zsbKVbMCxgQDVy5NA0_gH/view

**Comment by KaKi87** [comment]
Also note that I found one workaround to this issue : changing file name.

**Comment by proninyaroslav** [comment]
This is flaw in Android's Storage Access Framework: at the moment when I delete a file to replace with new, SAF still has not yet updated the information that the file doesn't exist and the downloader tries to access it to allocate the required size for the new file. I decided that it was not necessary to delete the file, it's enough to truncate its size up to 0, it eliminates the problem.
