### ISSUE TITLE
Error while downloading

### ISSUE THREAD

**Issue by FaizKhan5** [TachibanaGeneralLaboratories/download-navi#14]
Excepted Ok, but received partial 
Everytime i see this error on any file type of any size. 

Huawei Mate 10 Lite 
Android 8.0.0

**Comment by Gymcap** [comment]
This is apparently fixed in [3003249](https://github.com/TachibanaGeneralLaboratories/download-navi/commit/30032491700f4ee3d19b9e0b615f2f7293e1526a). I hope they post a new release build soon. Sadly, it doesn't seem functional at the moment.

**Comment by Pentaphon** [comment]
I came here to report the same issue. It prevents the app from downloading anything at all.

**Comment by proninyaroslav** [comment]
@Pentaphon 
Please wait 1.0.2 version.

**Comment by Pentaphon** [comment]
@proninyaroslav You may want to roll out 1.0.2 as a hotfix as soon as possible because there are probably thousands of people looking at the front page of F-Droid right now wondering why this new download manager can't seem to download anything.

**Comment by proninyaroslav** [comment]
@Pentaphon 
There is one more error, but I still haven't received the log from the user. Therefore, the release is delayed.

**Comment by Osoolo** [comment]
finally a open source download manger thank you , but can't download anything , waiting for the fix .

**Comment by proninyaroslav** [comment]
Please wait 1.0.2 in couple of days.
