### ISSUE TITLE
[Bug] Not using content-disposition for file name

### ISSUE THREAD

**Issue by KaKi87** [TachibanaGeneralLaboratories/download-navi#144]

**Comment by proninyaroslav** [comment]
Content-disposition is used. Can you give an example of such a link?

**Comment by KaKi87** [comment]
Here is one : https://unrestrict.kaki87.net/downloadFile/d746b076-02f8-4c1f-96fc-2ad99f232681
File name is `ubuntu-20.04.2-live-server-amd64.iso`.
Download Navi :
![](https://i.goopics.net/ekg35.png)
`wget` :
```
wget --content-disposition https://unrestrict.kaki87.net/downloadFile/d746b076-02f8-4c1f-96fc-2ad99f232681
--2021-04-27 13:32:32--  https://unrestrict.kaki87.net/downloadFile/d746b076-02f8-4c1f-96fc-2ad99f232681
Resolving unrestrict.kaki87.net (unrestrict.kaki87.net)... 148.251.48.170
Connecting to unrestrict.kaki87.net (unrestrict.kaki87.net)|148.251.48.170|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1215168512 (1,1G) [application/x-iso9660-image]
Saving to: ‘ubuntu-20.04.2-live-server-amd64.iso’
```

**Comment by proninyaroslav** [comment]
Hmm, works fine
![Screenshot_1619532864](https://user-images.githubusercontent.com/7840559/116256681-141a8e00-a77c-11eb-813b-fa63460c2f9d.png)

As far as I remember, I fixed it, but it was not included in the release. Please wait for release.
