### ISSUE TITLE
[Bug] Failed to determine if is child of

### ISSUE THREAD

**Issue by KaKi87** [TachibanaGeneralLaboratories/download-navi#147]
Hello,

When accidentally trying to download a file that was already previously downloaded using a different link, the original file got deleted from storage, and any further attempt will output this error :

> Failed to determine if (...) is child of (...)

Thanks

**Comment by proninyaroslav** [comment]
Seems a duplicate of https://github.com/TachibanaGeneralLaboratories/download-navi/issues/137

**Comment by proninyaroslav** [comment]
Can you attach a complete logcat or error message?

**Comment by KaKi87** [comment]
Unfortunately I was using Android TV on a proprietary Home Cinema player 😅

**Comment by proninyaroslav** [comment]
And no chance to use adb?

**Comment by KaKi87** [comment]
I don't think so.
Here's the device model : Zappiti Mini 4K HDR

**Comment by KaKi87** [comment]
Closing in favor of #137, please see demo there.
