### ISSUE TITLE
Downloads Fail

### ISSUE THREAD

**Issue by smaragdus** [TachibanaGeneralLaboratories/download-navi#15]
Almost all downloads I tried failed, showing the following error:

`Error: Expected OK, but received partial`

**Screen:**

![Download Navi - 2019-04-22 - error - 001](https://user-images.githubusercontent.com/9025757/56532839-38c14700-655f-11e9-83a4-23031c408c67.png)

This happens with all kinds of files (APK, EPUB, FB2, PNG, ZIP, etc). I am using **Download Navi** (version [1.0.1](https://github.com/TachibanaGeneralLaboratories/download-navi/releases/tag/1.0.1), [F-Droid release](https://f-droid.org/en/packages/com.tachibana.downloader/), Android 8).

**Download Navi** has a nice interface and offers a good set of features but it simply fails to download files on my device.

**Comment by c-sanchez** [comment]
I have a bunch of crashes with Download Navi too, But I'm a little lazy to make a report.
I'm waiting for next release to try then and check to see if it's been improvided :p

**Comment by proninyaroslav** [comment]
Please wait 1.0.2 in couple of days.
