### ISSUE TITLE
Can't download from 123putlocker.io

### ISSUE THREAD

**Issue by abelfn** [TachibanaGeneralLaboratories/download-navi#153]
I always download movies from 123putlocker.io using idm on my pc.

But After i found some android browser with video sniffer capability i decide to download movies from android using the sniffer but all browser with video sniffer gets the download link but fails to download the movie.

https://s04.eplayvid.com/vids/spiral.from.the.book.of.saw.2021.720p.hdcam.slotslights___60a18ed950972.mp4

EX browser:- Monument, phoenix, pure(only old version working for me).

They all download from other site but not from 123putlocker.io including download navi.

Ex:- go to github.com with monument browser and clik the download icon when loading finshed and download one of the video or copy the download link and paste it in download navi it will work.

I wonder why it can't download on android but works on pc with idm.

**Comment by proninyaroslav** [comment]
Why did you decide that this is a Download Navi problem?

**Comment by abelfn** [comment]
As I said if idm on pc can download it why not on android.

and also you have created this issue 

https://github.com/TachibanaGeneralLaboratories/download-navi/issues/85

and when you implement this enhancment how do you responed to the issue i created now.

b/c i had such problem with pure browser with referer, it can download from https://www.pixiv.net/ but not from oceanofapk.com due to pure browser always add referer to header which oceanofapk doesn't require, but if u add referer to the request it will not work.

But loaderdroid will work from both sites without error b/c it checks whether it requires referer or not 

I think you probably fixed this issue here

https://github.com/TachibanaGeneralLaboratories/download-navi/commit/0cdac285409499eab4c440a34c7a80b5605acbc1

i haven't tried it yet.

if idm can download it on pc, other android browsers including download navi probably incorrectly implemented http connection or smth is wrong with the implementation and have to check how idm able to download it.

**Comment by proninyaroslav** [comment]
Comparing session HTTP pakcages will probably help to determine what is happening on PC and Android and what's the difference. Or, at the very least, you must provide the error that Navi displays.

**Comment by abelfn** [comment]
Did you mean this

Download Navi:-

![DownloadNavi](https://user-images.githubusercontent.com/70645835/119185144-18864e00-ba7f-11eb-8164-46907db838ef.jpg)

Monument:-

![Monument](https://user-images.githubusercontent.com/70645835/119185577-8763a700-ba7f-11eb-8461-d9262fadea4d.jpg)

**Comment by proninyaroslav** [comment]
Have you tried using the built-in browser?

**Comment by abelfn** [comment]
Got this

![DownloadNavi](https://user-images.githubusercontent.com/70645835/119186467-d100c180-ba80-11eb-983d-f73bde703251.jpg)

**Comment by abelfn** [comment]
@proninyaroslav the new pure browser even though it shows 400 bad request,when i enter the direct downlosd link that is .mp4 link it will say do tap to download and it will download it.

![Uploading pure.jpg…]()

**Comment by abelfn** [comment]
![pure](https://user-images.githubusercontent.com/70645835/119198438-0661db00-ba92-11eb-9cab-028527a02bb8.jpg)

**Comment by abelfn** [comment]
![pure](https://user-images.githubusercontent.com/70645835/119199066-1928df80-ba93-11eb-9347-6c782dd8d8d3.jpg)

**Comment by proninyaroslav** [comment]
I receive HTTP 400 on a PC browsers.

**Comment by abelfn** [comment]
I don't get it 

this two shows 400 bad request:-

https://www.askapache.com/online-tools/http-headers-tool/

https://www.httpdebugger.com/Tools/ViewHttpHeaders.aspx


but this one shows 200 ok:-

http://www.rexswain.com/httpview.html

**Comment by abelfn** [comment]
Why is this closed?

This two download manager downloads the video directly.

Go to https://wvw1.123movies.net with monument browser
https://m.apkpure.com/monument-browser-ad-blocker-privacy-focused/br.marcelo.monumentbrowser

and copy download link and paste it to below download manager

![mb](https://user-images.githubusercontent.com/70645835/156534245-0f6f510e-77bc-4d4c-a750-52299fa49299.jpg)


ttps://m.apkpure.com/1dm-adblock-browser-video-torrent-downloader/idm.internet.download.manager

![1dm](https://user-images.githubusercontent.com/70645835/156532855-cec8794b-790a-438c-ab08-e6e0406e8797.jpg)

![1dm2](https://user-images.githubusercontent.com/70645835/156532883-9382ecea-588b-4a20-b958-abe2487c8b7a.jpg)


https://m.apkpure.com/video-downloader/video.downloader.videodownloader

![vd](https://user-images.githubusercontent.com/70645835/156532920-dc491602-1241-4ebe-ae6c-6abc0de82db1.jpg)

Download Navi

![dn](https://user-images.githubusercontent.com/70645835/156532980-550e71f9-9304-4d5e-ae90-d35370002cdb.jpg)


I tried different apps but only this 2 download manager and pure browser able to download it.
To me looks like smt missing in the header request.

**Comment by corxcv** [comment]
Finally problem solved!!!

the problem is the Referer 

Incase link expired go and get download link using idm
https://123movies.net/watch/Nx4lmgOx-the-unbearable-weight-of-massive-talent.html

1. https://s02.eplayvid.net/vids/the_unbearable_weight_of_massive_talent_2022___6272409201ba3.mp4
2. Add this to download navi referer input field https://eplayvid.net/

The problem is the way you check whether it requires referer or not 
https://github.com/TachibanaGeneralLaboratories/download-navi/issues/176
