### ISSUE TITLE
[Discussion] Potentially malicious Download Navi clone on Google Play

### ISSUE THREAD

**Issue by KaKi87** [TachibanaGeneralLaboratories/download-navi#154]
[Here](https://play.google.com/store/apps/details?id=download.manager.lemez).

Considering that the only other app that this account has published is a "cleaner and battery saver" ([here](https://play.google.com/store/apps/details?id=com.Clean.Lemez)), I suspect that both, at least, contains bloatware, at worst, malware.

But, I'm only reporting here because I didn't actually checked my theory.

If needed, I'll report to Google if you confirm this.

**Comment by proninyaroslav** [comment]
Obviously this is a clone (it also doesn't work :) ). I would be grateful if you send a report.

**Comment by KaKi87** [comment]
Do we only report for OSS license violation, or also malware ?

**Comment by proninyaroslav** [comment]
Can't tell if it's malicious

**Comment by KaKi87** [comment]
Ah, too bad. Alright

**Comment by proninyaroslav** [comment]
@xibr 
Nothing to do with it. They can be blocked, but they will appear again
