### ISSUE TITLE
[Request] Remove "Permission denied" dialog after showing it once 

### ISSUE THREAD

**Issue by Blocked** [TachibanaGeneralLaboratories/download-navi#155]
On newer devices, it is easier to provide access to a specific directory in storage using SAF instead of providing full access to storage.

This already works with all types of files as long SAF is used to specifically grant access to a folder in Settings >Storage > Default directory. But a annoying permission denied dialog shows up every time almost on every action and every time the app is opened. Consider adding "Do not show again. I understand the implications" checkmark at the bottom of the  permission denied dialog.

**Comment by proninyaroslav** [comment]
In the new version, I will leave only SAF (due to migration on Android 11 API) and remove the classic access to fs via permission. What kind of dialog do you mean?

**Comment by Blocked** [comment]
@proninyaroslav  There is a "Permission denied" dialog which shows up every time I try to add a download and sometimes when I open. the app.

The dialog that reads:

"Permission denied 

Without this permission app can't save files in memory on some devices and versions of Android. The app will not work properly. Are you sure you want to deny this permission?"

**Comment by proninyaroslav** [comment]
Ah, I got it.

**Comment by proninyaroslav** [comment]
Fixed https://github.com/TachibanaGeneralLaboratories/download-navi/commit/a90eab8b98c59c9cd63b07a13564f7784e8f7261. Now if you select "Don't ask again" in the system dialog, Navi will not inform you about it.
