### ISSUE TITLE
brickworkratings.com: HTTP 404

### ISSUE THREAD

**Issue by proninyaroslav** [TachibanaGeneralLaboratories/download-navi#162]
Example URL: https://www.brickworkratings.com/Admin/PressRelease/Nutraplus-India-23Mar2021%20.pdf

**Comment by xibr** [comment]
This is because the space in the file name should be like this 
https://www.brickworkratings.com/Admin/PressRelease/Nutraplus-India-23Mar2021%20.pdf

**Comment by proninyaroslav** [comment]
@xibr 
No, the problem is that `www` is needed to work correctly. Navi removes `www` by default.

**Comment by xibr** [comment]
you are correct.

**Comment by proninyaroslav** [comment]
Same here https://www.careratings.com/upload/CompanyFiles/PR/09072021072014_Tag_Offshore_Limited.pdf
