### ISSUE TITLE
Allow name field to be automatically populated with the filename?

### ISSUE THREAD

**Issue by Pentaphon** [TachibanaGeneralLaboratories/download-navi#17]
Why do we have to enter the name each time we add a link? Why can't it just download the link? The name field should be optional IF we want to change the filename, which most of the time, we do not. 

This is with the latest 1.0.2 on Android 7.1.2

**Comment by proninyaroslav** [comment]
You must click the Connect button. I think it's worth adding an automatic connect option.

**Comment by proninyaroslav** [comment]
Implemented 2f1094b

**Comment by Pentaphon** [comment]
Thanks @proninyaroslav 

You may want to do that by default since it is very annoying to be be prompted to enter a filename every single time. People just want to paste the link and download immediately, not go through more steps.

**Comment by proninyaroslav** [comment]
I set it by default as enabled. I will not remove this buttons, because a user may simply not want to wait for a connection or he can't make a connection at the moment.

**Comment by Pentaphon** [comment]
@proninyaroslav That's fine, but you may want to consider changing the "connect" button to say "download" instead to avoid any confusion. It should be clear that button means "download now".

**Comment by proninyaroslav** [comment]
"Download" isn't suitable, because this means download the file.
