### ISSUE TITLE
Improve and fix Arabic translation

### ISSUE THREAD

**Issue by xibr** [TachibanaGeneralLaboratories/download-navi#171]
There are some spelling errors in the Arabic translation and also some incorrect translations, for example
https://github.com/TachibanaGeneralLaboratories/download-navi/blob/d82e36ed8c3a9ecdd5789d4a93defae78e4430b5/app/src/main/res/values-ar/strings.xml#L162
Also here
https://github.com/TachibanaGeneralLaboratories/download-navi/blob/d82e36ed8c3a9ecdd5789d4a93defae78e4430b5/app/src/main/res/values-ar/strings.xml#L219-L226

Also in this case we don't need to add much, we can keep only two. Also, the translation is incorrect.
https://github.com/TachibanaGeneralLaboratories/download-navi/blob/d82e36ed8c3a9ecdd5789d4a93defae78e4430b5/app/src/main/res/values-ar/strings.xml#L116-L123

```
<plurals name="unable_sharing" tools:ignore="MissingQuantity">
        <item quantity="one">لا يمكن مشاركة الملف.</item>
        <item quantity="other">لا يمكن مشاركة الملفات.</item>
    </plurals>
```

**Comment by proninyaroslav** [comment]
You can translate here https://crowdin.com/project/download-navi
