### ISSUE TITLE
Google Drive download issued .bin instead .zip etc.

### ISSUE THREAD

**Issue by Kita2345** [TachibanaGeneralLaboratories/download-navi#172]
Google Drive Downloaded not in .zip, .img etc. but in strange file names and .bin file extension.

**Comment by Kita2345** [comment]
1.4

**Comment by Kita2345** [comment]
See
https://github.com/aria2/aria2/pull/1587

**Comment by proninyaroslav** [comment]
@Kita2345 
Is's related to wrong extension?

**Comment by proninyaroslav** [comment]
Getting content size is fixed https://github.com/TachibanaGeneralLaboratories/download-navi/commit/ade6fc31e9ebb6fb18e8202ddc90df3fedf4761d

**Comment by proninyaroslav** [comment]
Filename parsing is also fixed, the problem showed up with all downloads, not just GDrvie  c9cc8d9
