### ISSUE TITLE
"Not found" on Google Play Store anymore?

### ISSUE THREAD

**Issue by Pentaphon** [TachibanaGeneralLaboratories/download-navi#173]
The listing on Google Play was removed. What happened? @proninyaroslav

**Comment by proninyaroslav** [comment]
Thank you for informing me. I don't yet know what the reason is, because another person publish it on Play. As soon as information appears, I will inform additionally.

**Comment by Pentaphon** [comment]
> Thank you for informing me. I don't yet know what the reason is, because another person publish it on Play. As soon as information appears, I will inform additionally.

It seems to be back now, but we haven't gotten 1.4 from it yet.

**Comment by proninyaroslav** [comment]
I hope he will soon publish this version.

**Comment by Pentaphon** [comment]
> I hope he will soon publish this version.

Still now 1.4 on Google Play after 5 days.

**Comment by proninyaroslav** [comment]
@Pentaphon 
I hope he gets in touch.
