### ISSUE TITLE
Can't open apk files

### ISSUE THREAD

**Issue by rektpartyaftermath** [TachibanaGeneralLaboratories/download-navi#174]
# Problem
App can't open/install apk files, its says"Can't find correct application for this action".

**Comment by proninyaroslav** [comment]
Please provide screenshots of the filename and dialog.

**Comment by rektpartyaftermath** [comment]
![Screenshot_2021-08-04-00-20-45-96](https://user-images.githubusercontent.com/76981805/128059693-823d28ea-b14e-41fd-b6b2-53f7f9d1c109.png)

**Comment by proninyaroslav** [comment]
Have you allowed installation from unknown sources as well as from Navi source?

**Comment by rektpartyaftermath** [comment]
i just find an option to install from unknown source, it was on.

**Comment by rektpartyaftermath** [comment]
as far as i know, my phone doesn't have option to allow installation from specific app, its just set globally, across all application.

**Comment by proninyaroslav** [comment]
Maybe your firmware just doesn't support this?

**Comment by rektpartyaftermath** [comment]
but my built in download manager can do it, and download manager on chrome.
i find same problem midori browser.
maybe my phone have different way of installing application.

**Comment by proninyaroslav** [comment]
Can you specify the model and OS version?

**Comment by rektpartyaftermath** [comment]
Oppo a37f
Android 5.1.1

**Comment by proninyaroslav** [comment]
Feel free to reopen if the issue is still actual.
