### ISSUE TITLE
Data Uri not supported 

### ISSUE THREAD

**Issue by Kita2345** [TachibanaGeneralLaboratories/download-navi#175]
https://dopiaza.org/tools/datauri/examples/index.php

Picture cannot be downloaded

HTML contained in Uri is not displayed

**Comment by proninyaroslav** [comment]
This requires two things to be implemented:
1. An attempt to enable iframe in WebView (so far I don't know how successful it will be)
2. Implementation of support for downloading from `data:` links (including base64 decoding): https://stackoverflow.com/questions/46579237/download-file-from-base64-url-in-android-webview
