### ISSUE TITLE
Feature request: auto retry when timed out or failed

### ISSUE THREAD

**Issue by abda11ah** [TachibanaGeneralLaboratories/download-navi#177]
Can you please add a function to automatically relaunch a failed download?

Because on slow connection sometimes the server closes the connection and got a timed-out error (download failed). The download can restart from its last position but this have to be launched manually.

It should automatically retry download every x minutes.

**Comment by proninyaroslav** [comment]
Have you tried using the `Retry` option in the add dialog?
![Screenshot_1629558571](https://user-images.githubusercontent.com/7840559/130326198-11f42c11-5431-4e20-9648-846e83605514.png)

**Comment by abda11ah** [comment]
I don't remember if i clicked on this checkbox
I will try again as soon as I need to download a large file.

**Comment by proninyaroslav** [comment]
Feel free to reopen if the issue is still actual.

**Comment by KaKi87** [comment]
Hello,
That option doesn't work when a download timeouts immediately after starting.
Thanks
