### ISSUE TITLE
[Bug] Visiting page redirects to data:image/svg+xml

### ISSUE THREAD

**Issue by Kita2345** [TachibanaGeneralLaboratories/download-navi#178]
Describe the bug
When visiting the page mentioned below, it first loads the page, but then automatically redirects to "data:image/svg+xml,%3Csvg xlmns='http://www.w3.org/2000/svg' width='980' height='551'/%3E". On the default Android browser and on Fenix, the page loads just fine.

To Reproduce

Go to https://tweakers.net/reviews/8806/harvest-moon-one-world-beter-maar-nog-steeds-tegenvallend.html
See error
Expected behavior
Page shown properly.

**Comment by proninyaroslav** [comment]
This is because JS code, contained in the website, makes this redirect. I fixed it by checking redirects for URL validity.
