### ISSUE TITLE
Grind House skate shop shows blank

### ISSUE THREAD

**Issue by Kita2345** [TachibanaGeneralLaboratories/download-navi#181]
Blank page when visiting the following web site:
https://www.grindhouse.eu/

Sounds like an issue with WebView as it works on Chrome and does not with DuckDuckGo. Almost looks like the redirect is not working. Works on GeckoView with Firefox Focus.

**Comment by proninyaroslav** [comment]
Looks like WebView doesn't have the required certificate to load the page:

`Failed to validate the certificate chain, error: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.`

I don't think I can do something in this situation.

**Comment by Kita2345** [comment]
I think this out to be a 301 redirect issue

**Comment by proninyaroslav** [comment]
In any case, it's necessary to have certificates on the device.
