### ISSUE TITLE
Website non-text content not rendering

### ISSUE THREAD

**Issue by Kita2345** [TachibanaGeneralLaboratories/download-navi#186]
On this page: https://money.cnn.com/data/fear-and-greed

None of the charts show up
![Screenshot_2021-09-09-05-27-02-07_3bf0dca51f420a078e6c41b69eb6f015](https://user-images.githubusercontent.com/87817690/132593960-9c186ea0-c326-4d87-ab73-de21c686aecc.jpg)

**Comment by proninyaroslav** [comment]
I give this errors:
`Mixed Content: The page at 'https://money.cnn.com/data/fear-and-greed/' was loaded over HTTPS, but requested an insecure image 'http://markets.money.cnn.com/Marketsdata/uploadhandler/z6f8f7c0az54e3f1959e7d4b84936a97e4b5835226.png'. This request has been blocked; the content must be served over HTTPS.", source: https://money.cnn.com/.element/ssi/head/5.1/user-consent-3.1.5.js`

I turned on the compatibility mode for mixed content. This should work.
