### ISSUE TITLE
Error parsing filename and unknown file extension

### ISSUE THREAD

**Issue by Kita2345** [TachibanaGeneralLaboratories/download-navi#187]
example
https://pan.tpcraft.cn/api/v3/file/source/7/Java8%2064%E4%BD%8D.exe?sign=TuX1WLnbXtd0V7RmoFDvvmqgMN8EmVNs03xeacaNqGA%3D%3A0
![Screenshot_2021-09-12-02-04-54](https://user-images.githubusercontent.com/87817690/132958739-68978b5b-ab98-43e2-871f-2b10540ce7f2.jpg)

**Comment by proninyaroslav** [comment]
The reason is incorrect Conten-Disposition format:
`attachment;filename*=utf-8''f3I5VzTa%5FJava8%2064%E4%BD%8D%2Eexe;filename="f3I5VzTa_Java8 64%E4%BD%8D.exe"`

I will think about how to handle this case.

**Comment by proninyaroslav** [comment]
Fixed. I also sent the fix to Firefox Mobile team, it has the same problem https://github.com/mozilla-mobile/android-components/pull/11055
