### ISSUE TITLE
Not download external file

### ISSUE THREAD

**Issue by junior012** [TachibanaGeneralLaboratories/download-navi#19]
not work save file on external micro sd 64gb

**Comment by proninyaroslav** [comment]
Not enough information. Do you choose the path from the system file manager?

**Comment by junior012** [comment]
Yes,but not download file😥

**Comment by proninyaroslav** [comment]
I think app showed an error. Please show it to me

**Comment by junior012** [comment]
Can you teach me how to logcat the app?

**Comment by proninyaroslav** [comment]
Make a screenshot and write log with Logcat Reader app.

**Comment by junior012** [comment]
This error:
558.mp4 Error: Invalid UUlD string: 7436-720A

**Comment by proninyaroslav** [comment]
Please make a log so I can fix it soon

**Comment by junior012** [comment]
This screenshot https://send.firefox.com/download/2b20f5858a00a941/#KPQtty7I0PSuaAZv0WENHQ

**Comment by proninyaroslav** [comment]
Please install Logcat Reader from F-Droid or Play, there you will find the record button (circle). Run Download Navi, add the download and wait for the error. After that, stop recording and save log to the file.

**Comment by junior012** [comment]
Logcat: https://send.firefox.com/download/9ca02e606dd041d5/#IqczrFBkptd10P51F03OXg

**Comment by proninyaroslav** [comment]
Try disabling "Pre-allocate disk space" option in Behavior settings

**Comment by proninyaroslav** [comment]
Step 2: please install this APK with fix, enable "Pre-allocate disk space" and try downloading again.
[app-release.zip](https://github.com/TachibanaGeneralLaboratories/download-navi/files/3122214/app-release.zip)

**Comment by proninyaroslav** [comment]
@junior012
Any results? I would like to add this fix in 1.0.3, but if today there will be no results, then I will publish a release without it.

**Comment by junior012** [comment]
I wait

**Comment by proninyaroslav** [comment]
What are you waiting for?  If the error didn't appear after the first download, then the fix worked (step 2).

**Comment by junior012** [comment]
I'm sorry, I meant I'm not rushed

**Comment by proninyaroslav** [comment]
1.0.3 will be released in about 8-10 hours, if you have time during this time range, it will be very good.

**Comment by junior012** [comment]
Ah ok I will try the apk you gave me

**Comment by junior012** [comment]
Now is work in download externa file sd 👍
https://send.firefox.com/download/e876592d9f50e286/#GGMxcVB-a5Gqb1X3IeChXQ

Thanks

**Comment by proninyaroslav** [comment]
With enabled "Pre-allocate disk space", yes?

**Comment by junior012** [comment]
@proninyaroslav Yes
