### ISSUE TITLE
Not getting the file size

### ISSUE THREAD

**Issue by abelfn** [TachibanaGeneralLaboratories/download-navi#194]
https://f-droid.org/repo/me.austinhuang.instagrabber_65_src.tar.gz

Download navi

![dn](https://user-images.githubusercontent.com/70645835/136991858-7ee71cb6-2e7a-447b-84b0-295852ebaff2.jpg)

LoaderDroid

![ld](https://user-images.githubusercontent.com/70645835/136991903-dcd53f6e-540b-4f97-8b44-5accbee77562.jpg)

**Comment by proninyaroslav** [comment]
Very strange indeed. It does not return a `Content-Length` header specifically in Navi. I tried to remove any extra headers and user agent and it didn't work.

**Comment by proninyaroslav** [comment]
Well, as it turns out OkHttp removes the `Content-Length` header in the response if it's doing transparent gzip. The solution is to specify `Accept-Encoding: identity` in the request header.
