### ISSUE TITLE
The downloader isn't working. I get an error everytime.

### ISSUE THREAD

**Issue by HarryHeights** [TachibanaGeneralLaboratories/download-navi#20]
![Screenshot_2019-04-27-06-46-57-212_com tachibana downloader](https://user-images.githubusercontent.com/40593824/56845376-5b819180-68b8-11e9-82c5-8727605ac882.png)

**Comment by proninyaroslav** [comment]
Fixed in 1.0.2.

**Comment by HarryHeights** [comment]
Thanks. It's working now. It's very fast. Do you have a privacy policy? I could help create it for you.

**Comment by proninyaroslav** [comment]
Any help is appreciated.

**Comment by HarryHeights** [comment]
Alright @proninyaroslav . I'll create the content and send a PR.
