### ISSUE TITLE
Wrong filename 

### ISSUE THREAD

**Issue by Kita2345** [TachibanaGeneralLaboratories/download-navi#200]
Link
https://www.rki.de/SharedDocs/Bilder/InfAZ/neuartiges_Coronavirus/Coronavirus_BzGA_Covid_19_Seite.jpg;jsessionid=1507A3BCFE9968D4FC6374EC2B05DE4A.internet052?__blob=normal&v=1

**Comment by proninyaroslav** [comment]
Looks like Firefox (mobile and desktop) has the same problem except for Chromium.

**Comment by Kita2345** [comment]
Issue still occur it on Android 9

**Comment by Kita2345** [comment]
![Screenshot_20220215-100024~2](https://user-images.githubusercontent.com/87817690/153984812-e7ac0486-c1b7-4417-99c4-479d061bd64c.png)
