### ISSUE TITLE
Error: Unhandled HTTP response: 404 Not Found

### ISSUE THREAD

**Issue by ahmedmujtabanizamani** [TachibanaGeneralLaboratories/download-navi#205]
when i am downloading file from our local storage server, it gives error during download and stoped downloading, then i have to resume it manually, even i checked retry button but it does not seems retrying on that error plz add auto retry feature work on that error.
![Screenshot_2021-12-26-17-46-42-91_3bf0dca51f420a078e6c41b69eb6f015](https://user-images.githubusercontent.com/44010174/147408825-0d8af68e-eab8-43cd-b6c5-19315925d367.jpg)

**Comment by proninyaroslav** [comment]
You can choose `Retry` option during the adding of URL.
