### ISSUE TITLE
[Android 12] Unable to run pending downloads

### ISSUE THREAD

**Issue by TeaqariaWTF** [TachibanaGeneralLaboratories/download-navi#207]
![Screenshot_20220105-150747](https://user-images.githubusercontent.com/90970076/148215624-f6872d8a-bcc0-4b0c-bd5b-c2582ec4056e.png)
other files do not resume the download after one download is complete .

**Comment by proninyaroslav** [comment]
Have you tried a reset of settings?

**Comment by TeaqariaWTF** [comment]
> Have you tried a reset of settings?

yes i tried that it didn't work

**Comment by proninyaroslav** [comment]
To check, I set the maximum number of active downloads to 1. And it works:
![Screenshot_1641626424](https://user-images.githubusercontent.com/7840559/148635678-feeb16d0-b4a9-4cf6-a9e3-67bfea856745.png) ![Screenshot_1641626430](https://user-images.githubusercontent.com/7840559/148635681-23980676-ea25-4330-823e-bb84a0a21efe.png)

Did you restart the app or device at this moment?

**Comment by TeaqariaWTF** [comment]
> Did you restart the app or device at this moment? To check, I set the maximum number of active downloads to 1. And it works:
> 
> ![Screenshot_1641626424](https://user-images.githubusercontent.com/7840559/148635678-feeb16d0-b4a9-4cf6-a9e3-67bfea856745.png) ![Screenshot_1641626430](https://user-images.githubusercontent.com/7840559/148635681-23980676-ea25-4330-823e-bb84a0a21efe.png)

I cleared app data, uninstalled and re-downloaded the app but nothing worked

**Comment by proninyaroslav** [comment]
Can you take a video with the steps to reproduce the problem?

**Comment by TeaqariaWTF** [comment]
Sorry for the delay, here's the video link :https://gofile.io/d/6MUYJ1

**Comment by TeaqariaWTF** [comment]
![Uploading Screenshot_20220118-153753.png…]()
hence my canceled downloads

**Comment by TeaqariaWTF** [comment]
![Uploading Screenshot_20220118-153753.png…]()


hence my canceled downloads

**Comment by proninyaroslav** [comment]
No, I meant a video with step by step adding downloads and the moment when they get stuck.

**Comment by TeaqariaWTF** [comment]
![Screenshot_20220118-153753](https://user-images.githubusercontent.com/90970076/149986900-6a41533b-a5bf-4ff8-96b6-693b8ea03350.png)

hence my canceled downloads

**Comment by TeaqariaWTF** [comment]
I hope it will be enough


https://gofile.io/d/ejOpIM

**Comment by proninyaroslav** [comment]
Are you using Android 12?

**Comment by TeaqariaWTF** [comment]
> Are you using Android 12?

yes i am using android 12

**Comment by proninyaroslav** [comment]
Ok, I was able to reproduce this bug in Android 12. As it turns out, Navi can't run/extend itself in the background, this logic was necessary to keep the app running in the background. These are the new restrictions of Android 12 https://developer.android.com/guide/components/foreground-services#background-start-restriction-exemptions. We need to figure out how to get around these restrictions or refactor the running logic.

**Comment by TeaqariaWTF** [comment]
> Ok, I was able to reproduce this bug in Android 12. As it turns out, Navi can't run/extend itself in the background, this logic was necessary to keep the app running in the background. These are the new restrictions of Android 12 https://developer.android.com/guide/components/foreground-services#background-start-restrictions. We need to figure out how to get around these restrictions or refactor the run logic https://developer.android.com/guide/components/foreground-services#background-start-restriction-exemptions.

I don't know anything about this, I hope there is a way

**Comment by proninyaroslav** [comment]
Thank you for reporting. This is a serious problem that affects the app work.

**Comment by TeaqariaWTF** [comment]
> Thank you for reporting. This is a serious problem that affects the app work.

Will there be an update soon?

**Comment by proninyaroslav** [comment]
Currently I'm working on another feature, and I think it will take 1-2 weeks.

**Comment by TeaqariaWTF** [comment]
> Currently I'm working on another feature, and I think it will take 1-2 weeks.

Thank you for your quick response.  I will wait for the next update

**Comment by proninyaroslav** [comment]
I didn't have time to fix it in the current release, please wait.

**Comment by proninyaroslav** [comment]
@TeaqariaWTF 
As a temporary workaround, you can disable battery optimization for Navi https://driversnote.helpscoutdocs.com/article/137-android-battery-saving-settings

**Comment by TeaqariaWTF** [comment]
> @TeaqariaWTF As a temporary workaround, you can disable battery optimization for Navi https://driversnote.helpscoutdocs.com/article/137-android-battery-saving-settings

yes, that's how I solved the error, sorry I forgot to inform you

**Comment by proninyaroslav** [comment]
@TeaqariaWTF 
If somehow or other I can't get around this problem, then maybe this will be the only solution.

**Comment by TeaqariaWTF** [comment]
> @TeaqariaWTF Bir şekilde bu sorunu çözemezsem, belki de tek çözüm bu olacaktır.

It would be better to add a warning screen on the first launch of the application instead of extra hassle.

**Comment by TeaqariaWTF** [comment]
> @TeaqariaWTF If somehow or other I can't get around this problem, then maybe this will be the only solution.

When you open the application, it may give a small warning

**Comment by TeaqariaWTF** [comment]
![Screenshot_20220205-230431_ADM](https://user-images.githubusercontent.com/90970076/152657144-f4ec29cd-1254-4c91-a133-95a76e2a5b83.png)
there may be a warning screen similar to this

**Comment by proninyaroslav** [comment]
I decide to show a dialog for the user to disable battery optimization.
