### ISSUE TITLE
Download failure for retrieve certification from specific website

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [TachibanaGeneralLaboratories/download-navi#212]
I just try to download https://piasecki.com/wp-content/uploads/2021/01/piasecki_transparent.png and then I receive the following IO error message on screen:
> java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

Is there any way to work around?

**Comment by proninyaroslav** [comment]
I tried to download and everything is fine. This means that your device doesn't have a root certificate. Navi doesn't have an option to disable SSL certificate verification as it's dangerous.

**Comment by Kita2345** [comment]
Error occurred on Android 5

**Comment by proninyaroslav** [comment]
This site uses Let's Encrypt certificate, which no longer works on Android 5 and below https://scotthelme.co.uk/lets-encrypt-old-root-expiration/. Navi uses the system certificate store.

**Comment by Kita2345** [comment]
Try this https://greenscene.co.id/wp-content/uploads/2021/05/Arlong-696x497.jpg

**Comment by proninyaroslav** [comment]
It also uses Let's Encrypt certificate.

**Comment by Kita2345** [comment]
I tried to download and everything is fine on Android 5

**Comment by proninyaroslav** [comment]
This problem may not be with all Android 5 devices.

**Comment by proninyaroslav** [comment]
Similar to https://github.com/TachibanaGeneralLaboratories/download-navi/issues/18
