### ISSUE TITLE
Https  response 503, but webview can download

### ISSUE THREAD

**Issue by hsoftxl** [TachibanaGeneralLaboratories/download-navi#215]
https://ps.romsforever.cc/PS2/PAL-EU/Sonic%20Unleashed%20%28Europe%2C%20Australia%29%20%28En%2CFr%2CDe%2CEs%2CIt%29.7z

can not download,

**Comment by proninyaroslav** [comment]
Duplicate of https://github.com/TachibanaGeneralLaboratories/download-navi/issues/213
