### ISSUE TITLE
Request Access to all files permission to download to sdcard

### ISSUE THREAD

**Issue by riedel** [TachibanaGeneralLaboratories/download-navi#218]
Seems like MANAGE_EXTERNAL_STORAGE or WRITE_EXTERNAL_STORAGE is not requested as I can only write to media files on Android 12

**Comment by proninyaroslav** [comment]
You can freely select SD card, just press to system file manager button

**Comment by riedel** [comment]
Thanks, it seems that you now need to create new directories for security reasons. E.g. just writing to download is not possible. However creating a subdirectory works.
