### ISSUE TITLE
Doesn't support HTTP Basic Auth

### ISSUE THREAD

**Issue by bakaouji** [TachibanaGeneralLaboratories/download-navi#23]
If you have some files protected by Basic Auth (example https://jigsaw.w3.org/HTTP/Basic/ ), it's not possible to provide download-navi a username/password in order to authenticate.

Apart from providing username/passwords, it should also be possible to save them as well.

**Comment by proninyaroslav** [comment]
it's already planned https://github.com/TachibanaGeneralLaboratories/download-navi/issues/7
