### ISSUE TITLE
Exclude junrar from F-Droid build

### ISSUE THREAD

**Issue by linsui** [TachibanaGeneralLaboratories/download-navi#242]
Could you please exclude junrar from F-Droid build? It's licensed under UnRAR, which is not an open source license. https://fedoraproject.org/wiki/Licensing:Unrar F-Droid [will block junrar](https://gitlab.com/fdroid/fdroidserver/-/merge_requests/1091). We'd like to make sure affected apps are updated. Sorry for the unconvience.

**Comment by proninyaroslav** [comment]
I didn't know that `junrar` is licensed under a freeware license. I will remove it completely, thanks.

**Comment by linsui** [comment]
Thanks!

**Comment by proninyaroslav** [comment]
Will be released today.

**Comment by linsui** [comment]
Thanks!
