### ISSUE TITLE
not support https://mirrors.ustc.edu.cn

### ISSUE THREAD

**Issue by ivysrono** [TachibanaGeneralLaboratories/download-navi#27]
Example: https://mirrors.ustc.edu.cn/lineageos/full/oneplus3/
get wrong file just 5B

**Comment by proninyaroslav** [comment]
This site uses JavaScript and requires a wait of 2 seconds before starting the download. Quite interesting. I will have to study this mechanism.

**Comment by ivysrono** [comment]
BTW, ADM is OK for this site.

**Comment by ivysrono** [comment]
1.1 still

**Comment by proninyaroslav** [comment]
I think this will be resolved only after the browser implementation https://github.com/TachibanaGeneralLaboratories/download-navi/issues/29

**Comment by proninyaroslav** [comment]
So, the browser has the same behavior with this link. I will try to fix it.

**Comment by proninyaroslav** [comment]
Works well in Navi Browser (built-in browser).
