### ISSUE TITLE
Some Download Url doesn't open and work

### ISSUE THREAD

**Issue by n3m001** [TachibanaGeneralLaboratories/download-navi#28]
when I want to download something from this type of url 

http://cdn.bossbd.net/Tutorial/Programming%20Tutorial%20For%20Beginners%20Learn%20C%20Plus%20plus%20in%202%20hours.rar

it shows server error returned HTTP 400 code.I can't download.Please solve the problem.

**Comment by proninyaroslav** [comment]
I tested and this link works and the file is downloaded.
