### ISSUE TITLE
Add internal browser

### ISSUE THREAD

**Issue by NikhilSudhakaranVG** [TachibanaGeneralLaboratories/download-navi#29]
Add internal browser , unlike pc can't integrate this with browser

**Comment by KaKi87** [comment]
Just like ADM, I agree that this is a great idea.

**Comment by annada-behera** [comment]
Yes. I believe this should be a feature. Many websites do not allow their files to be hot linked. So, when downloading from such site, if the browser and downloading apps are different, the server detects the change and refuses to serve the files.

Also, it can be used to download files from

**Comment by KaKi87** [comment]
Hey there, any news on this ? Thanks

**Comment by proninyaroslav** [comment]
Maybe in the next release.

**Comment by KaKi87** [comment]
Hello, any ETA on next release ? Thanks

**Comment by proninyaroslav** [comment]
Not earlier than next month

**Comment by abelfn** [comment]
@proninyaroslav can i send you my web browser integrated with download navi.
may be you could modifie it.

**Comment by proninyaroslav** [comment]
@abelfn Thank you, but the browser is almost ready. You can contribute later when I commit the changes.

**Comment by proninyaroslav** [comment]
Implemented 6749e9f6e5d7534c99ffa39be06fec07dc4b3287, 2463f850862b33a7fffc207d0bff5c4a4ce9ea6a

**Comment by KaKi87** [comment]
Nice ! Can we get an APK ? 😊

**Comment by proninyaroslav** [comment]
@KaKi87 The release will be soon
