### ISSUE TITLE
Allow us to set default # of pieces and default user agent so we don't have to select it with every new download

### ISSUE THREAD

**Issue by Pentaphon** [TachibanaGeneralLaboratories/download-navi#32]
I'd like a way to set Download Navi to always download with a default number of pieces and useragent so I don't have to select them every time I download something. For example, I like to download things at 4 pieces and have my useragent be a Firefox browser. Can we get something like that in the settings page so we can customize it once and never have to select those options again when adding a new download?

**Comment by proninyaroslav** [comment]
Implemented https://github.com/TachibanaGeneralLaboratories/download-navi/commit/3bd6f20aa66fd6cab3c22eab44cb47d7bdbf2737
