### ISSUE TITLE
Theme Change - Requires App Restart

### ISSUE THREAD

**Issue by hl2guide** [TachibanaGeneralLaboratories/download-navi#33]
Currently changing the theme requires a manual app restart.

Please consider mentioning this in the settings section. 👍

**Comment by proninyaroslav** [comment]
I added the snackbar with button to automatically restart after changing the theme 5ef167b
![Screenshot_1574523345](https://user-images.githubusercontent.com/7840559/69481194-05051300-0e07-11ea-91fe-a5b1010221c8.png)
