### ISSUE TITLE
Preserve file extension when renaming a file?

### ISSUE THREAD

**Issue by Pentaphon** [TachibanaGeneralLaboratories/download-navi#34]
Hi, right now the rename function doesn't seem to preserve the filename. For example, if I download "music.mp3" and rename it to "song" it just saves as "song" with no file extension. It should save as song.mp3. I realize I could just type "song.mp3" but that seems completely unnecessary. I will rarely, if ever, have to change the file extension because I'm downloading the exact type of file I want. Can we have an option so that when renaming a file, it only changes the filename and not the extension? Thanks.

**Comment by proninyaroslav** [comment]
Implemented https://github.com/TachibanaGeneralLaboratories/download-navi/commit/d3d4a6453fff1275381e831750efd53870c88f37
