### ISSUE TITLE
[Request] Checksums comparition

### ISSUE THREAD

**Issue by AreYouLoco** [TachibanaGeneralLaboratories/download-navi#35]
It would be nice to specify a chechsum at the time of adding a file and checking over it at the end of the download.

**Comment by proninyaroslav** [comment]
Implemented 50cd85e494d5806e8a5e186f44a8538aa50182bd

**Comment by AreYouLoco** [comment]
Cool! F-droid release to test?

**Comment by proninyaroslav** [comment]
This will be in 1.1.1 which will be released within 1-2 days. F-droid is slow so wait.

**Comment by AreYouLoco** [comment]
Sure thing!
