### ISSUE TITLE
can't open apk files

### ISSUE THREAD

**Issue by bingoxo** [TachibanaGeneralLaboratories/download-navi#36]
it says "all apps associated with this action have been turned off , blocked , or are not installed"
i tried giving it permission to install unknown apps (had to go to app info , but it would be better if there is a shortcut within the app) but still nothing changed

**Comment by proninyaroslav** [comment]
I didn't observe such a message in the stock Android, could you provide a screenshot? I think this is the problem of your firmware. In addition, Android always asks permission to install from unknown sources.

**Comment by proninyaroslav** [comment]
If the problem persists and the above tips don't help, please open issue again.

**Comment by subpub** [comment]
Same problem here. (Can't open apk files; Doesn't show package installer) I'm using Stock Android 9, Zenfone m1. 

I _think_  the problem is with the intent it sends



```
 intent://com.tachibana.downloader.provider/root/storage/emulated/0/Download/materialdialog%2Baffelostad.apk#Intent;scheme=content;type=application/octet-stream;launchFlags=0x3000000;end 
------------ 
ACTION: android.intent.action.VIEW 
DATA: content://com.tachibana.downloader.provider/root/storage/emulated/0/Download/materialdialog%2Bafollestad.apk 
MIME: application/octet-stream 
URI: intent://com.tachibana.downloader.provider/root/storage/emulated/0/Download/materialdialog%2Bafollestad.apk#Intent;scheme=content;type=application/octet-stream;launchFlags=0x3000000;end 
FLAGS: 
FLAG_ACTIVITY_FORWARD_RESULT 
FLAG_ACTIVITY_PREVIOUS_IS_TOP 

------------ 
MATCHING ACTIVITIES: 
*unrelated apps*
```





 with this intent from another app it works






```
intent://com.android.providers.downloads.documents/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2Fmaterialdialog%2Bafollestad.apk#Intent;scheme=content;type=application/vnd.android.package-archive;launchFlags=0x3000000;end 
------------ 
ACTION: android.intent.action.VIEW 
DATA: content://com.android.providers.downloads.documents/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2Fmaterialdialog%2Bafollestad.apk 
MIME: application/vnd.android.package-archive 
URI: intent://com.android.providers.downloads.documents/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2Fmaterialdialog%2Bafollestad.apk#Intent;scheme=content;type=application/vnd.android.package-archive;launchFlags=0x3000000;end 
FLAGS: 
FLAG_ACTIVITY_FORWARD_RESULT 
FLAG_ACTIVITY_PREVIOUS_IS_TOP 

------------ 
MATCHING ACTIVITIES: 
Package installer (com.google.android.packageinstaller - com.android.packageinstaller.InstallStart) 

------------ 
onActivityResult: 
resultCode: 0 
 
```

**Comment by proninyaroslav** [comment]
Can you send a sample link to the APK? I see that it could not determine MIME type.

**Comment by subpub** [comment]
Sure
https://github.com/afollestad/material-dialogs/raw/master/sample/sample.apk

Note that I changed the name

**Comment by proninyaroslav** [comment]
Github returns MIME type as `octet-stream`. It's probably worth adding a MIME type definition by file extension.

![mime](https://user-images.githubusercontent.com/7840559/73054813-448dc100-3e83-11ea-8202-d96641fb437f.png)
