### ISSUE TITLE
Downloads complete, notification stuck

### ISSUE THREAD

**Issue by opusforlife** [TachibanaGeneralLaboratories/download-navi#37]
![Screenshot_20190521](https://user-images.githubusercontent.com/50522836/58071639-dfaff780-7b8c-11e9-885a-c6ba4570a3f0.png)

These downloads show up in the 'Completed' tab, and they play just fine. But the notification is stuck there, as you can see. Tapping 'Shutdown' from the menu does nothing.

Force stopping the app clears them up, as expected.

This *might* have been caused by adding lots of new downloads without letting previous ones complete.

**Comment by proninyaroslav** [comment]
Hi. Suppose a progress notification stuck, but does the finish notification still appear?

**Comment by proninyaroslav** [comment]
Fixed https://github.com/TachibanaGeneralLaboratories/download-navi/commit/7ea302041c9761f639d0c755230e9ee12fc74f9d

**Comment by opusforlife2** [comment]
Hey. It's been long enough that I don't remember that detail at all, sorry. I would have had to test with several simultaneous downloads again.

Glad to see it fixed, though. Thanks!
