### ISSUE TITLE
Inaccurate translations

### ISSUE THREAD

**Issue by Wilker-a** [TachibanaGeneralLaboratories/download-navi#42]
during the usage of the program i am seeing a few inaccurate translations while it is shown in my language (e.g "resume" meing shown as "resumar" instead of "retomar")

is there a page on [weblate](https://hosted.weblate.org/) i can use to help with translations?

edit.typo

**Comment by proninyaroslav** [comment]
You can translate it on Crowdin https://crowdin.com/project/download-navi

**Comment by Wilker-a** [comment]
thank you
