### ISSUE TITLE
[Bug] Current speed mismatch

### ISSUE THREAD

**Issue by AreYouLoco** [TachibanaGeneralLaboratories/download-navi#43]
Hi I have faced issue with non consistency with the actual download speed.

I have choosen 8 pieces per download and notification speed seems to indicate speed for only one of the parts while the main window of the app shows correct speed for the download.

Attaching screenshots to prove my point.

![Screenshot_20190914-165148](https://user-images.githubusercontent.com/6299176/64909786-bfdea980-d710-11e9-9ac8-36b4879cac19.png)
![Screenshot_20190914-165140](https://user-images.githubusercontent.com/6299176/64909790-c79e4e00-d710-11e9-9fd9-c153f000b2fa.png)
![Screenshot_20190914-165131](https://user-images.githubusercontent.com/6299176/64909792-ce2cc580-d710-11e9-8a49-0274f89fa15d.png)

**Comment by AreYouLoco** [comment]
Also the remaining time to accomplish is calculated wrong because of slower speed indicated. But fixing the actual speed should make a good calculation.

**Comment by proninyaroslav** [comment]
Fixed https://github.com/TachibanaGeneralLaboratories/download-navi/commit/07f6327ab4c5d769e2da77c875f2697a2d5ab8aa
