### ISSUE TITLE
Support for download APKs from APKMirror

### ISSUE THREAD

**Issue by rodrigoswz** [TachibanaGeneralLaboratories/download-navi#44]
Whenever I try to download something from APKMirror using Navi, I have this error:
![APKMirror using Navi](https://i.imgur.com/Wkcud44.png)

But when I try with ADM, works normally:
![APKMirror using ADM](https://i.imgur.com/4GoCUds.png)

Of course, APKMirror for now is the only site that realized this happens, there may be others as well.

**Comment by proninyaroslav** [comment]
Thank you, I will take a look.

**Comment by proninyaroslav** [comment]
Which browser do you use?

**Comment by rodrigoswz** [comment]
> Which browser do you use?

Kiwi Browser

**Comment by proninyaroslav** [comment]
Fixed https://github.com/TachibanaGeneralLaboratories/download-navi/commit/523d247a061d9ad56972755513b64a406af02088

**Comment by rodrigoswz** [comment]
Wow thank you! Looking forward to uninstall ADM 😏
