### ISSUE TITLE
Language selection ?

### ISSUE THREAD

**Issue by KaKi87** [TachibanaGeneralLaboratories/download-navi#45]
Hello,

I can't find out how do I change the app's language,

My phone language is set on french and I'm french.

Thanks

**Comment by proninyaroslav** [comment]
The app language depends on the system language. It seems I didn't merge Italian and French from Crowdin. Thank you for telling me about this. I will merge them into repo today.

**Comment by KaKi87** [comment]
Thanks.

Despite automation is great, I also think it would be nice to provide an override menu, just in case.

Le 1 déc. 2019 à 11:20, à 11:20, Yaroslav Pronin <notifications@github.com> a écrit:

**Comment by proninyaroslav** [comment]
Android has pretty crappy methods for dynamically changing the language, UI, colors, and more. I don’t think this is a good idea, as it creates additional crappy code in the app.

**Comment by KaKi87** [comment]
Are you saying that most of all multilingual apps on Android are crappy?

Isn't there an i18n module or something like that which should do the work properly?
Le 1 déc. 2019, à 11:37, Yaroslav Pronin <notifications@github.com<mailto:notifications@github.com>> a écrit:

Android has pretty crappy methods for dynamically changing the language, UI, colors, and more. I don’t think this is a good idea, as it creates additional crappy code in the app.

**Comment by proninyaroslav** [comment]
I mean the dynamic change of language in the code. Language in Android is a resource file, like i18n. There is no problem with this unless you try to change the resource in the code. This should be done by the system, as conceived in Android.

**Comment by KaKi87** [comment]
Even on a properly configured Android device, there are at least two use cases where a language override can be useful :

1. The app isn't available in the user's language but he knows another supported language better than english

2. The app translation in the user's language is not satisfying and he wants to use another one, generally the developer's one, which is better translated

There may be some other cases where the user would like to change a specific app's language...

**Comment by proninyaroslav** [comment]
I understand you. You are talking about programmatically change of language. Programmatically changing the language in Android is terrible. Changing the language on Android at runtime was never officially encouraged or documented. The resource framework automatically selects the resources that best match the device.

**Comment by proninyaroslav** [comment]
I updated the project languages, you can compile it with French 18ccec6401b30f5ebe0f901f19cfaa7bcc358aa8. I close this issue, you can open a separate language switch issue
