### ISSUE TITLE
F-Droid Summary

### ISSUE THREAD

**Issue by uniqx** [TachibanaGeneralLaboratories/download-navi#51]
F-Droid will update how we display summary text in our next app release. Summary text will now always be highlighted and prepended to the long app description.

Your long description text starts with the same text you've got in your summary. This will look redundant. I recommend to remove the summary text from your long description.

here are more infos/screenshots about this update: [fdroidclient!855](https://gitlab.com/fdroid/fdroidclient/merge_requests/855)

**Comment by proninyaroslav** [comment]
Ok, with the next release.

**Comment by proninyaroslav** [comment]
Updated
