### ISSUE TITLE
Tapping Download finished Notification launches wrong apps

### ISSUE THREAD

**Issue by rancidfrog** [TachibanaGeneralLaboratories/download-navi#53]
When I click on notification of download finished for an mp4 file it does not suggest video players at all,
![](https://i.imgur.com/KkVJGIS.png)

Clicking opens up,
![](https://i.imgur.com/HdDtoYo.png)

Not sure why Ankidroid is suggested, Instead of having vlc, gallery, video player, and other video players

**Comment by proninyaroslav** [comment]
I checked and it works fine. Can you send a link so that I can reproduce the problem?

**Comment by rancidfrog** [comment]
Currently this happens on all mp4 files I download. Might be an android issue then, as I have not updated for a while

**Comment by proninyaroslav** [comment]
Choose any example that doesn’t work and send it.

**Comment by rancidfrog** [comment]
Also mkv is not being identified as video file, which triggers wrong app on click, both notification and main app.
It seems that there is an issue identifying download formats

**Comment by proninyaroslav** [comment]
@rancidfrog 
I cannot solve your problem until you provide me with a download link example that doesn't work correctly.

**Comment by proninyaroslav** [comment]
Please check it in 1.2, feel free to open again.
