### ISSUE TITLE
Stop triggers wrong download from notification  

### ISSUE THREAD

**Issue by rancidfrog** [TachibanaGeneralLaboratories/download-navi#54]
I was downloading three items using app.
After stopping one of the first two items, the third last download stops downloading.
So I tried downloading again the 3rd item and stopped from notification one of the first two, and again the last downloaded item is stopped and not the one I clicked on.
Stopping in main UI worked as intended.
There is no point of having stop and pause icon if they are not working properly:
![](https://i.imgur.com/g8mkfjo.png)

**Comment by proninyaroslav** [comment]
Do I understand correctly that pressing stop button in the notification stops a completely different download?

**Comment by rancidfrog** [comment]
Yes.
Also, happens for clicking completed download. If there is more than 1 completed it sometimes tries to open the other completed file, not the one clicked

**Comment by proninyaroslav** [comment]
Fixed 2448475
