### ISSUE TITLE
Some file hosts cause issues with App

### ISSUE THREAD

**Issue by rancidfrog** [TachibanaGeneralLaboratories/download-navi#55]
App unable to handle download links from certain file hosts.
I.E.

mixdrop.co
![](https://i.imgur.com/IQ5DXMD.png)

clicknupload.co
![](https://i.imgur.com/lZzIRwy.png)

**Comment by proninyaroslav** [comment]
The first error occurs because the server makes too many redirects. The second error is more interesting, it seems that it doesn't correctly handle port 80 at the end of the URL.

**Comment by rancidfrog** [comment]
How does the normal android system download manager handle too many redirects?
What are app limitations?

**Comment by proninyaroslav** [comment]
In this case, this is not the app limit, but the server limit. In the app there are 5 redirects.

**Comment by proninyaroslav** [comment]
Fixed `8080` port handling: https://github.com/TachibanaGeneralLaboratories/download-navi/commit/443d86d5ffa8ef75e7be96329687bbf1064a41b0
