### ISSUE TITLE
option to set default connection count

### ISSUE THREAD

**Issue by r3dhash** [TachibanaGeneralLaboratories/download-navi#58]
I've to manually select 16 connections on "advanced download" for every file

it would be cool if you could bump it up to 32 parts/connections per download

idm+ only lets you download upto 2gb in sdcard(with 32 parts download), but navi can automa. move the file from internal to sd which is lovely af

**Comment by proninyaroslav** [comment]
Implemented https://github.com/TachibanaGeneralLaboratories/download-navi/commit/3bd6f20aa66fd6cab3c22eab44cb47d7bdbf2737

**Comment by KaKi87** [comment]
Hello @proninyaroslav, when will this feature be published on Google Play ? Thanks

**Comment by proninyaroslav** [comment]
@KaKi87 
Hi. 1.3 version already in Play.

**Comment by KaKi87** [comment]
I do have v1.3, but pieces count keeps resetting as it always had...

**Comment by proninyaroslav** [comment]
@KaKi87 
Navi saves the last set number of pieces.

**Comment by KaKi87** [comment]
So, I found out my issue : pièces number is forgotten after a failed download.
