### ISSUE TITLE
Open app from download progress notification

### ISSUE THREAD

**Issue by KaKi87** [TachibanaGeneralLaboratories/download-navi#59]
1. Open your web browser
2. Click on a downloadable file
3. Select Navi on the "open with" menu
4. Click on "add" from Navi's modal
5. Open status bar
6. Click on Navi's download progress notification

Expected behavior : Navi opens

Actual behavior : nothing happens

Thanks

**Comment by proninyaroslav** [comment]
I didn't envisage opening Navi by clicking on a download notify, as you can click the foreground notification to get the same effect. If necessary, I can make it.

**Comment by KaKi87** [comment]
Why does the foreground notification exists in the first place ? Would it be possible to only have the download progress notification and click on it to open Navi ? Thanks.

**Comment by proninyaroslav** [comment]
@KaKi87 
Please see here https://github.com/TachibanaGeneralLaboratories/download-navi/issues/86

**Comment by KaKi87** [comment]
Thanks ! Yet my issue is still valid, isn't it ?

**Comment by proninyaroslav** [comment]
If you want navi to open when you click on progress, I can do this.

**Comment by KaKi87** [comment]
Yes, thanks !

**Comment by vdbhb59** [comment]
Good suggestion tbvh

**Comment by proninyaroslav** [comment]
Implemented 8d639a4
