### ISSUE TITLE
addDialog file name problem 

### ISSUE THREAD

**Issue by abelfn** [TachibanaGeneralLaboratories/download-navi#63]
can't use sybols in file name field
![20200408_165953](https://user-images.githubusercontent.com/63355586/78793190-b83b6680-79ba-11ea-97f5-f8d7a8183ba5.jpg)

example video url
https://m.youtube.com/watch?v=DTK4eRzcRyI
it will not work for any videos title that have ? symbols and others
it will work for ! and others

**Comment by proninyaroslav** [comment]
This sign is forbidden for FAT32, I turned on this check by default for all downloads.

**Comment by abelfn** [comment]
if i use vidmate it work
what can i do about it

**Comment by proninyaroslav** [comment]
@abelfn Just don't use this symbol (?).

**Comment by abelfn** [comment]
ok thank you very much for such amazing download manager, the one and the only i have found that works.
by the way i have made video downloader using yours download navi
any way i try will use filename.replace("\?", "");

**Comment by proninyaroslav** [comment]
I hope your video downloader is open source ;)

**Comment by jwmh** [comment]
Q, what about prompting user or adding a setting to autoreplace/delete special characters? Make it fewer clicks.

**Comment by proninyaroslav** [comment]
Added https://github.com/TachibanaGeneralLaboratories/download-navi/issues/65
