### ISSUE TITLE
In some cases of network problems, the download possition can't be returned and remain with pause button

### ISSUE THREAD

**Issue by nam108** [TachibanaGeneralLaboratories/download-navi#66]
As in title. I know there is a resume downloading option and that in some cases it might not work, because some servers doesn't allow partial downloading but in my case it's not a case and sometimes when my network crashed when downloading I could not resume the downloading and also the play/pause button on the left is always showing pause icon.
Setting for deleting file if error is off but maybe what happened in my case is that there was an error and that's why the file doesn't want to continue downloading? If that's the case, maybe it would be useful to have at least some information popping up what happened?

**Comment by proninyaroslav** [comment]
Does the download have any error or does it remain on the pause tab? Can you collect a logcat? Probably, I could understand the reason, this is clearly not normal.

**Comment by nam108** [comment]
Thanks for concern. They are remaining on the "queued" tab. I can get the logcat, but can you little guide me how to do that. I guess I need some logcat app and then? And I don't know if it's not an issue but I don't have root also.

**Comment by proninyaroslav** [comment]
You can do this with ADB on your PC, without root.

**Comment by nam108** [comment]
Ok I can "google" how to do that, but do you need the whole cat log or only part and if part which part?

**Comment by proninyaroslav** [comment]
You start the logcat record and after that try to resume the download. This is the part of the log you should send

**Comment by abelfn** [comment]
in my case data is turned on but no internet or 0 balance make it pause button unchangeable/unclickable to play button

**Comment by proninyaroslav** [comment]
@abelfn Yes, that’s the normal. You can turn it off in settings.

**Comment by nam108** [comment]
> @abelfn 
Sorry for so late. Here logcat:
https://bin.snopyta.org/?c86fab33572f2443#7dx6QxhzQQTJamWNcr4N7eXPKvJYdPNPRgjfuVkwvqXW
Pwd I sent by PM

**Comment by proninyaroslav** [comment]
Probably you didn't make log at the moment when the error occurred? If this is not possible for you, you can backup the app data using any available backup utility to get the database and send me

**Comment by nam108** [comment]
I cleaned the log before starting downloader and saved after few secs after pushing the pause buttons in the downloader.
One more try:
https://bin.snopyta.org/?3c32742fdfd73b30#2NaRTG7SRHa6MtFQ47rmFxTxiyCLYA1BPh2MNb5UE4Am
Same pwd.
Backup apps needs root I guess, which I don't have.

**Comment by proninyaroslav** [comment]
@nam108 
You misunderstood. You have to make a log when you try to resume download, not pause

**Comment by nam108** [comment]
Yes, that's what I am doing - I am trying to resume the downloads by pressing the pause icon that is there.

**Comment by proninyaroslav** [comment]
@nam108 
There seems to be no errors or messages. Try to backup the app via ADB, this should not require root https://android.stackexchange.com/questions/28296/how-to-fully-backup-non-rooted-devices

**Comment by nam108** [comment]
I will try, but what is our program name/what exactly would be the abd command?
From the link, general is: adb backup -apk -shared -all -nosystem -f backup.ab
I guess our would be something like: `adb backup -apk -shared -nosystem -f backup.ab <downloader.navi>`?

**Comment by nam108** [comment]
Ok, I found, the command was: adb backup -apk -noshared -nosystem -f backup.ab com.tachibana.downloader
https://file.io/rs1KrxMP
same pwd

**Comment by proninyaroslav** [comment]
Page not found. Please re-upload this archive.

**Comment by nam108** [comment]
https://send.firefox.com/download/49414f5574c63f2a/#g-h5p59G5F86n-4OZS4dJQ

**Comment by proninyaroslav** [comment]
Hmm, the database is empty. During backup, the download wasn't deleted?

**Comment by proninyaroslav** [comment]
Which of these downloads have problems?
![Снимок экрана от 2020-05-23 18-34-52](https://user-images.githubusercontent.com/7840559/82734527-28603a80-9d24-11ea-94a2-753dd4ff10ae.png)

**Comment by nam108** [comment]
All

**Comment by proninyaroslav** [comment]
All of these downloads have a "Waiting for network connection" status. Perhaps your network is in roaming or it's metered?

**Comment by nam108** [comment]
Yes - all of them have "waiting..." status. My network is not in roaming.
I could add more links from this website and they are working.
I was trying also quickly to reproduce this error, but without success - I always could resume the downloads.
I don't remember exactly what happened before with the network that they went in such mode.

**Comment by proninyaroslav** [comment]
I will try to figure it out. Perhaps this is a bug in one of the libraries.

**Comment by nam108** [comment]
I am not sure if this might be important, because I couldn't reproduce this error later, but those files with the problem were saved on OTG usb pendrive.
OS is Miui 11 (Android 9)

**Comment by abelfn** [comment]
I am having serious problem!!

![dn](https://user-images.githubusercontent.com/70645835/92327568-65b8b180-f00f-11ea-9683-88fdba639533.gif)

![logcat ](https://user-images.githubusercontent.com/70645835/92327573-6bae9280-f00f-11ea-90ae-5a1a129e1d88.jpg)

I try to force stop the app and relaunch but can't pause it no matter what.

**Comment by proninyaroslav** [comment]
@abelfn 
Not enough information:
- Android version
- Available network type (unmetered, metered or roaming)
- Full logcat

**Comment by abelfn** [comment]
1. 8.1.0 
2. metered i bought premium
3. https://drive.google.com/file/d/1JICRxbc04QnMn3j1y4NEItZKSFqW0gvc/view?usp=sharing

**Comment by proninyaroslav** [comment]
@abelfn 
Are the "Unmetered connections only" or "Not roaming" options enabled in the settings?

**Comment by abelfn** [comment]
1. Unmetered connections only - disabled
2. Enable roaming - enabled, but i am not out of country.

**Comment by proninyaroslav** [comment]
@abelfn 
It's very strange, but it seems to be stuck waiting for the network. Moreover, there are no errors or messages about this in the log, which is very strange. I'm using WorkManager and network checking happens on its side. Maybe this is a bug in WorkManager, but I can't say for sure. I recently updated WorkManager, you can build the APK and try again after reinstalling.

**Comment by abelfn** [comment]
Ok, by the way I started translating DownloadNavi to Amharic in crowdin.

**Comment by proninyaroslav** [comment]
If the problem occurs in the new version, feel free to open it again.
