### ISSUE TITLE
Can't know size of download, giving up

### ISSUE THREAD

**Issue by abelfn** [TachibanaGeneralLaboratories/download-navi#69]
Download aborted because of it can't determine the file size.

even if the file size is in KB.

Other downloaders downloads even if they can't determine the file size.

link to the file url

programmerguru.com/verify-user/?tutorial=Android&download_file=AndroidBrightnessActivity

![er](https://user-images.githubusercontent.com/63355586/80744046-ba5e9400-8b26-11ea-900d-9162fcecb55f.jpg)

**Comment by proninyaroslav** [comment]
Thank you, I will check it

**Comment by proninyaroslav** [comment]
Fixed 814c9c90cbfb3d0010d5e3d14f52a277524afbc7
