### ISSUE TITLE
Not getting the corrent file name

### ISSUE THREAD

**Issue by abelfn** [TachibanaGeneralLaboratories/download-navi#71]
It's not getting the corrent file name.
even if the file name is included with the url.

i have this problem for yotube videos also, I thought it was my video downloader in the past and use a work around for it.

but now i don't think so.

site url
https://www.internetdownloadmanager.com/download.html

![idm](https://user-images.githubusercontent.com/63355586/80907382-6ff43780-8d1f-11ea-973b-d635e7cc4f18.jpg)

**Comment by proninyaroslav** [comment]
It will be fixed in the next version, see https://github.com/TachibanaGeneralLaboratories/download-navi/commit/7e2ac502fcda48c4f2ca20e17487e8278aefed30

![Screenshot_1588516307](https://user-images.githubusercontent.com/7840559/80916883-16622c00-8d64-11ea-8385-8336b90942ce.png)
