### ISSUE TITLE
Feature requests - per telegram group chat

### ISSUE THREAD

**Issue by vdbhb59** [TachibanaGeneralLaboratories/download-navi#74]
Hi Mate [@proninyaroslav],
Per the group chat [here](https://t.me/DownloadNavi/846), [here](https://t.me/DownloadNavi/847) and [here](https://t.me/DownloadNavi/848), attaching the images and video for the feature requests..
**01.** In completed download section, allow "remove all/select all" to remove. Also, "clear all".
**02.** Provide a dark theme, as the current bright/light/white theme is too bright and hurts the eyes at night.
**03.** Allow sorting of files in downloaded files section.
**04.** Allow sorting basis cataloguing (catalogue folders), as pre-defined ones. Probably, Pictures, Videos, Documents, Zipped, Media/Music, etc,.
05. Add some file formats, which may be missing.
![Remove All](https://user-images.githubusercontent.com/60728004/81478509-9e9c7180-923b-11ea-9ae2-4ef17a0c6939.jpg)
![Catalogue](https://user-images.githubusercontent.com/60728004/81478512-a3612580-923b-11ea-8afe-1390638fd7da.jpg)
![Catalogue](https://user-images.githubusercontent.com/60728004/81478520-b116ab00-923b-11ea-92b2-23aa08f56dfe.gif) - RENAME TO .MP4 & VIEW..

**Comment by vdbhb59** [comment]
Some suggestions regarding Navi browser:
1) add exit button below settings.
2) clicking on https Padlock🔒 gives basic certificate info about website.
3) Add home button in right menu top which takes us to browser home/startscreen
4) make default home page https://start.duckduckgo.com/ as this url won't show that annoying startup popups.
5) Add "downloads" button in right menu list which redirects on navi main download screen ui.
6) Add option to choose Browser Useragent from settings. same as in download popup.
7) Auto delete Cookies on exit & dedicated button in settings for "prefer HTTPS version of website 1st".

**Comment by proninyaroslav** [comment]
Issues by main features: #77, #78

**Comment by proninyaroslav** [comment]
Issues by browser features: #79, #80, #81, #82, #83, #84

**Comment by Oymate** [comment]
So close this?

**Comment by vdbhb59** [comment]
Should I close this, @proninyaroslav ?

**Comment by proninyaroslav** [comment]
@vdbhb59 
Yes you can do it.
