### ISSUE TITLE
paused download in progress in notification

### ISSUE THREAD

**Issue by ghost** [TachibanaGeneralLaboratories/download-navi#75]
Is this normal?

notification area

![notifi](https://user-images.githubusercontent.com/63355586/81987276-f83cdb80-9641-11ea-8c9a-04f558883b48.jpg)

main window area

![main](https://user-images.githubusercontent.com/63355586/81987342-199dc780-9642-11ea-9a1a-d0d5f40df3a0.jpg)

**Comment by proninyaroslav** [comment]
This is probably fixed here https://github.com/TachibanaGeneralLaboratories/download-navi/commit/244847529ba941db008a0d7fd1ad48997e92b4fa.

**Comment by abelfn** [comment]
this problem still exist in v1.2
