### ISSUE TITLE
Error when downloading certain files

### ISSUE THREAD

**Issue by Gymcap** [TachibanaGeneralLaboratories/download-navi#9]
```Error: Expected OK, but received partial```

I get this error when downloading files such as:   
• The release apk   
•  Files from [this](https://www.thinkbroadband.com/download) test site

Files download directly from the git repo fine.

_Android: 9   
Model: Nexus 6   
Manufacturer: motorola_

**Comment by proninyaroslav** [comment]
Fixed https://github.com/TachibanaGeneralLaboratories/download-navi/commit/30032491700f4ee3d19b9e0b615f2f7293e1526a
