### ISSUE TITLE
Download Navi Malicious App

### ISSUE THREAD

**Issue by abelfn** [TachibanaGeneralLaboratories/download-navi#92]
it didn't happen to other apps.

https://m.apkpure.com/virus-cleaner-antivirus-phone-clean-boost-master/virus.cleaner.antivirus.phone.security.boost

![DownloadNavi](https://user-images.githubusercontent.com/63355586/85183877-1c6d8700-b296-11ea-8b72-5dece2dbd49b.jpg)

**Comment by proninyaroslav** [comment]
Hi. Download Navi doesn't contain malicious code. Did you download the APK from official sources? They are listed on the main page. If you downloaded from unofficial sources, the APK may be infected with viruses. I also recommend checking your system with another antivirus, maybe it's just a mistake.

**Comment by abelfn** [comment]
@proninyaroslav its weird,after i uninstall and install it again the antivirus says no virus.I don't understand what caused the antivirus to throw warning.By the way i didn't download the apk from unofficial sources i just build the apk from the sourcecode i also checked other antivirus but reports no virus.It must be the antivirus problem.
