### ISSUE TITLE
[Bug] Browser redirects camera.aeonax.com to "data:text/html;"

### ISSUE THREAD

**Issue by KaKi87** [TachibanaGeneralLaboratories/download-navi#94]
![](https://i.goopics.net/9XNgg.png)

**Comment by abelfn** [comment]
It's working for me.

![aeonax
](https://user-images.githubusercontent.com/63355586/86056210-c521a080-ba65-11ea-911e-d814f69c23c9.jpg)

**Comment by KaKi87** [comment]
Well, it actually also works for me right now 😅
I don't know what happened, sorry for the inconvenience.
I'm hereby closing this issue.
