### ISSUE TITLE
Pinch Zooming not working properly if Address bar at the bottom disabled

### ISSUE THREAD

**Issue by ghost** [TachibanaGeneralLaboratories/download-navi#96]
if address bar at the bottom enabled pinch zoom work correctly.if it is disabled and address bar at the top not working correctly.
try this url 
http://zone-h.org/archive/special=1

**Comment by abelfn** [comment]
@proninyaroslav  the problem was NestedWebView  but i found full working NestedScrollWebView.
if u want it i will share u just let me know.

**Comment by proninyaroslav** [comment]
Fixed https://github.com/TachibanaGeneralLaboratories/download-navi/commit/66ff895b66a3d3179a0fa039e5148736be338a0a
