### ISSUE TITLE
file name parsing

### ISSUE THREAD

**Issue by dm9pZCAq** [TachibanaGeneralLaboratories/download-navi#98]
for example from url: `https://de8.libria.fun/get/YY6IbU-l-GJ3hN7mkuuAjQ/1594469128/mp4/8406/0003.mp4?download=Kanata no Astra-3-hd.mp4`

file name is: `Kanata%20no%20Astra-3-hd.mp4`
I think it should be: `Kanata no Astra-3-hd.mp4`

![image](https://user-images.githubusercontent.com/46228973/87229593-e1043b00-c3b1-11ea-8f60-60bcaa8c66d2.png)

**Comment by proninyaroslav** [comment]
Probably this is the server side name. If you have another valid URL to check, please reopen this issue again.
